### ISSUE TITLE
cli: add list output files command

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-client#38]
- [x] https://github.com/reanahub/reana-workflow-engine-yadage/issues/37: write workflow results to canonical location
- [x] https://github.com/reanahub/reana-workflow-controller/issues/38: add get workflow results endpoint
- [ ] https://github.com/reanahub/reana-server/issues/12: add get analysis output endpoint
- [ ] Implement CLI according to #22, as an example PR https://github.com/reanahub/reana-client/pull/42 which implements the call to the new status endpoint.
  - [ ] Copy last `server` OpenAPI spec.
  - [ ] Use bravado client to make the call and connect with click application [here]().
  - [ ] Test creating some files under `<analysis_dir>/outputs/` and `reana-client outputs list --workflow <uuid>`
