### ISSUE TITLE
cli: add download output files command

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-client#48]
- [x] https://github.com/reanahub/reana-workflow-engine-yadage/issues/37: write workflow results to canonical location
- [x] https://github.com/reanahub/reana-workflow-controller/issues/38: add get workflow results endpoint
- [x] https://github.com/reanahub/reana-server/issues/21: add download analysis output files endpoint
- [x] Implement CLI according to #22, as an example PR https://github.com/reanahub/reana-client/pull/42 which implements the call to the new status endpoint.
  - [x] Copy last `server` OpenAPI spec.
  - [x] Use bravado client to make the call and connect with click application [here]().
  - [x] Test creating some files under `<analysis_dir>/outputs/` and `reana-client outputs download <file_name> --workflow <uuid>`
