### ISSUE TITLE
cli: add start workflow command

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-client#49]
- [x] https://github.com/reanahub/reana-workflow-controller/issues/48: add start workflow endpoint
- [x] https://github.com/reanahub/reana-server/issues/22: add get analysis output endpoint
- [x] Implement CLI according to #22, as an example PR https://github.com/reanahub/reana-client/pull/42 which implements the call to the new status endpoint.
  - [x] Copy last `server` OpenAPI spec.
  - [x] Use bravado client to make the call to `reana-server` and connect with click application [here](https://github.com/reanahub/reana-client/blob/master/reana_client/cli/workflow.py#L181).
  - [x] Test using `reana-client create workflow -f <reana_spec_file>` save `analysis_uuid` and then call `reana-client workflow start --workflow <analysis_uuid>`
